baseURL = "https://p4lang.github.io/gsoc/blog/"
languageCode = "en-us"
title = "P4 GSoC Blog"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[pagination]
  pagerSize = 10
