name: DCO Assistant for First-Time Contributors

on:
  check_run:
    types: [completed]

jobs:
  dco-help:
    # https://github.com/p4lang/.github/blob/main/.github/workflows/dco-welcome-reusable.yml
    uses: p4lang/.github/.github/workflows/dco-welcome-reusable.yml@main
